// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zvykjqfadwvtdroibuas.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp2eWtqcWZhZHd2dGRyb2lidWFzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ5MTQxODYsImV4cCI6MjA1MDQ5MDE4Nn0.xv1CqJoWqXXKK4S6F-hrehQd2hfgcEcaObv9hRsP6lA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);